name: Checkin

on:
  pull_request:
  issue_comment:
  push:
  schedule:
    - cron: "0 20 * * *"    # 每天早上4点执行
    - cron: "0 23 * * *"    # 每天早上7点再次执行(预防出错)

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Ubuntu version
        run: |
          cat /etc/issue
          sudo lsb_release -a

      - name: Install Google Chrome (sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb)
        run: |
          sudo apt-get install -y libgbm1
          sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Install selenium
        run: |
          sudo wget -q -O /usr/bin/selenium.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar

      - name: Install php dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Checkin
        run: |
          sudo php ./run.php ${{ secrets.EMAIL }} ${{ secrets.PASSWORD }}
